version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'